"""Add is_approved field to users table

Revision ID: 5f92bfba0ec7
Revises: f713fa3b65a4
Create Date: 2025-12-25 20:24:49.885924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f92bfba0ec7'
down_revision: Union[str, None] = 'f713fa3b65a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))

    # Step 2: Set default value for existing rows (False for regular users)
    op.execute("UPDATE users SET is_approved = FALSE WHERE is_approved IS NULL")

    # Step 3: Make column non-nullable with server default
    op.alter_column('users', 'is_approved',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
