"""add user model preferences

Revision ID: b1bee26fdb57
Revises: adde7294324f
Create Date: 2025-12-18 16:28:42.234738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1bee26fdb57'
down_revision: Union[str, None] = 'adde7294324f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('session_id'), table_name='conversations')
    op.drop_index(op.f('idx_config_logs_changed_at'), table_name='credit_config_logs')
    op.drop_index(op.f('idx_config_logs_config_id'), table_name='credit_config_logs')
    op.drop_index(op.f('idx_config_logs_field'), table_name='credit_config_logs')
    op.alter_column('messages', 'process_info',
               existing_type=mysql.TEXT(),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.add_column('users', sa.Column('conversational_provider', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('conversational_model', sa.String(length=100), nullable=False))
    op.drop_index(op.f('email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'conversational_model')
    op.drop_column('users', 'conversational_provider')
    op.alter_column('messages', 'process_info',
               existing_type=mysql.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_config_logs_field'), 'credit_config_logs', ['field_name'], unique=False)
    op.create_index(op.f('idx_config_logs_config_id'), 'credit_config_logs', ['config_id'], unique=False)
    op.create_index(op.f('idx_config_logs_changed_at'), 'credit_config_logs', ['changed_at'], unique=False)
    op.create_index(op.f('session_id'), 'conversations', ['session_id'], unique=True)
    # ### end Alembic commands ###
