"""add is_super_admin field to users table

Revision ID: b657aff96690
Revises: 5f92bfba0ec7
Create Date: 2025-12-25 21:31:40.768678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b657aff96690'
down_revision: Union[str, None] = '5f92bfba0ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first to handle existing rows
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE users SET is_super_admin = FALSE WHERE is_super_admin IS NULL")

    # Now make it NOT NULL with default value
    op.alter_column('users', 'is_super_admin',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###
