"""Add model provider fields to messages

Revision ID: ca09c4d6c401
Revises: b1bee26fdb57
Create Date: 2025-12-18 16:37:26.392685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca09c4d6c401'
down_revision: Union[str, None] = 'b1bee26fdb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model_provider', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('model_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'model_name')
    op.drop_column('messages', 'model_provider')
    # ### end Alembic commands ###
