"""add_generation_model_preferences

Revision ID: f713fa3b65a4
Revises: ca09c4d6c401
Create Date: 2025-12-19 09:47:15.169857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f713fa3b65a4'
down_revision: Union[str, None] = 'ca09c4d6c401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_generation_provider', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('image_generation_model', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('video_generation_provider', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('video_generation_model', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'video_generation_model')
    op.drop_column('users', 'video_generation_provider')
    op.drop_column('users', 'image_generation_model')
    op.drop_column('users', 'image_generation_provider')
    # ### end Alembic commands ###
