"""Landing page export manager.

This module handles exporting landing pages as downloadable HTML files.
"""

import io
import zipfile
from datetime import datetime, timedelta
from typing import Any

import structlog

from app.modules.landing_page.models import ExportResult
from app.services.mcp_client import MCPClient, MCPError

logger = structlog.get_logger(__name__)


class ExportManager:
    """Landing page export manager.
    
    Handles exporting landing pages as complete HTML files with inline assets.
    """

    DOWNLOAD_EXPIRY_HOURS = 24

    def __init__(self, mcp_client: MCPClient):
        """Initialize export manager.
        
        Args:
            mcp_client: MCP client for Web Platform communication
        """
        self.mcp = mcp_client

    async def export(
        self,
        landing_page_id: str,
        html_content: str,
        user_id: str,
        format: str = "html",
    ) -> ExportResult:
        """Export landing page as downloadable file.
        
        Flow:
        1. Inline all CSS and JavaScript into HTML
        2. Package HTML into ZIP file
        3. Upload ZIP to S3 via MCP
        4. Generate presigned download URL with 24h expiration
        
        Args:
            landing_page_id: Landing page ID
            html_content: Complete HTML content
            user_id: User ID
            format: Export format (currently only "html" supported)
        
        Returns:
            ExportResult with download URL and expiration
        
        Raises:
            MCPError: If export fails
        """
        log = logger.bind(
            landing_page_id=landing_page_id,
            user_id=user_id,
            format=format,
            content_size=len(html_content),
        )
        log.info("export_start")

        try:
            # Step 1: Inline assets (CSS/JS already inline in generated HTML)
            inlined_html = self.inline_assets(html_content)

            # Step 2: Create ZIP file in memory
            zip_buffer = io.BytesIO()
            with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
                # Add index.html
                zip_file.writestr("index.html", inlined_html)
                
                # Add README with instructions
                readme_content = self._generate_readme(landing_page_id)
                zip_file.writestr("README.txt", readme_content)

            zip_data = zip_buffer.getvalue()
            file_size = len(zip_data)

            # Step 3: Upload ZIP to S3 via MCP
            file_key = f"exports/{user_id}/{landing_page_id}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.zip"
            
            upload_result = await self.mcp.call_tool(
                "upload_export_file",
                {
                    "file_key": file_key,
                    "content": zip_data.hex(),  # Send as hex string
                    "content_type": "application/zip",
                    "expiry_hours": self.DOWNLOAD_EXPIRY_HOURS,
                },
            )

            # Step 4: Get presigned download URL
            download_url = upload_result.get("download_url", "")
            expires_at = (
                datetime.utcnow() + timedelta(hours=self.DOWNLOAD_EXPIRY_HOURS)
            ).isoformat() + "Z"

            result = ExportResult(
                download_url=download_url,
                expires_at=expires_at,
                file_size=file_size,
            )

            log.info(
                "export_complete",
                download_url=download_url,
                file_size=file_size,
                expires_at=expires_at,
            )

            return result

        except MCPError as e:
            log.error(
                "export_failed",
                error=str(e),
                error_code=e.code,
            )
            raise

    def inline_assets(self, html: str) -> str:
        """Inline all CSS and JavaScript into HTML.
        
        For landing pages generated by our system, CSS and JS are already
        inline. This method ensures any external references are handled.
        
        Args:
            html: Original HTML content
        
        Returns:
            HTML with all assets inlined
        """
        # In our case, the generated HTML already has inline CSS/JS
        # This is a placeholder for future enhancement if we need to
        # fetch and inline external resources
        
        # Add meta tags for standalone usage
        if "<head>" in html and '<meta charset' not in html:
            html = html.replace(
                "<head>",
                '<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
            )
        
        return html

    def _generate_readme(self, landing_page_id: str) -> str:
        """Generate README file for export package.
        
        Args:
            landing_page_id: Landing page ID
        
        Returns:
            README content
        """
        return f"""Landing Page Export - {landing_page_id}
=====================================

This package contains your exported landing page.

Files:
------
- index.html: Your landing page (open this file in a browser)
- README.txt: This file

Deployment Instructions:
------------------------
1. Upload index.html to your web hosting service
2. Ensure the file is accessible via HTTPS
3. Test the page in multiple browsers
4. Monitor conversion tracking via Facebook Pixel

Notes:
------
- All CSS and JavaScript are embedded in the HTML file
- Facebook Pixel tracking code is included
- The page is optimized for mobile and desktop viewing
- For best performance, enable gzip compression on your server

Support:
--------
For questions or issues, please contact AAE support.

Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
"""
